import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bye",
  description: "Generated by create next app",
};

export default function ByeLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} bg-zinc-900  mb-5 h-full`}>
        {children}
      </body>
    </html>
  );
}
